### PR TITLE
fix: text view is not display in second activity

### PR DESCRIPTION
**Pull request by AlphaByte-RedTeam**

### CODE REVIEW

**Comment by AlphaByte-RedTeam** [comment]
Lama nih merge PR doang zzz

**Comment by AlphaByte-RedTeam** [comment]
bla bla bla bla bla

**Comment by AlphaByte-RedTeam** [comment]
ngang ngong ngang ngong

**Comment by janeclrst** [comment]
ARIGATOU GOZAIMASTAH, VERY" THANKYOU SO MUCH

**Comment by AlphaByte-RedTeam** [comment]
yaaa

**Pull request merged**
